name: Build macOS App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Build app
        run: |
          xcodebuild -project Benkei2.xcodeproj -scheme Benkei2 -configuration Release -derivedDataPath build

      - name: Code sign the app (if needed)
        run: |
          # Remove quarantine attributes that prevent execution
          find build/Build/Products/Release/Benkei2.app -type f -exec xattr -d com.apple.quarantine {} \; 2>/dev/null || true
          
      - name: Create distributable package
        run: |
          mkdir -p output
          cp -R build/Build/Products/Release/Benkei2.app output/
          # Make the executable properly executable
          chmod +x output/Benkei2.app/Contents/MacOS/Benkei2
          # Create a simple launcher script for easier execution
          cat > output/run-benkei2.sh << 'EOF'
          #!/bin/bash
          cd "$(dirname "$0")"
          open Benkei2.app
          EOF
          chmod +x output/run-benkei2.sh
          # Create installation instructions
          cat > output/README.txt << 'EOF'
          Benkei2 - macOSアプリケーション

          インストール手順:
          1. このzipファイルをApplicationsフォルダまたはお好みの場所に展開してください
          2. アプリケーションを実行するには:
             - Benkei2.appをダブルクリック、または
             - Benkei2.appが直接開かない場合はrun-benkei2.shをダブルクリック
          
          注意: macOSがセキュリティ警告を表示する場合は、以下の手順を実行してください:
          1. システム環境設定 > セキュリティとプライバシー を開く
          2. Benkei2に対して「このまま開く」をクリック
          
          または、ターミナルで以下のコマンドを実行してください:
          xattr -d com.apple.quarantine /path/to/Benkei2.app

          初回実行時にはアクセシビリティの許可が必要です。以下の手順に従ってください:
          1. システム環境設定 > セキュリティとプライバシー > プライバシー タブを開く
          2. 左側のリストから「アクセシビリティ」を選択
          3. 右側のリストにBenkei2.appが表示されていることを確認し、チェックボックスをオンにする
          EOF
          
      - name: Create zip package
        run: |
          cd output
          zip -r ../Benkei2-macOS.zip .
          
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Benkei2-macOS
          path: Benkei2-macOS.zip
